
(define true #t)
(define false #f)
(define null 'null)

(define global
    (environment
        identity
        handler
        (record 'env-type 'immutable)
        'send send
        'apply apply
        ...))

sexy-internal-abs
sexy-internal-apply
sexy-internal-bin-to-text
sexy-internal-ceil
sexy-internal-env-def!
sexy-internal-env-del!
sexy-internal-env-extend
sexy-internal-env-get
sexy-internal-env-has?
sexy-internal-env-lookup
sexy-internal-env-lookup-list
sexy-internal-env-mama
sexy-internal-env-partition
sexy-internal-env-set!
sexy-internal-env-size
sexy-internal-env-to-list
sexy-internal-env-to-record
sexy-internal-env-to-text
sexy-internal-floor
sexy-internal-get-object-type
sexy-internal-int-to-rune
sexy-internal-list
sexy-internal-list?
sexy-internal-list-ref
sexy-internal-list-to-text
sexy-internal-main-module
sexy-internal-not
sexy-internal-number-to-text
sexy-internal-object-answers?
sexy-internal-object-autos
sexy-internal-object-default
sexy-internal-object-get-message
sexy-internal-object-messages
sexy-internal-object-resends
sexy-internal-operator-to-text
sexy-internal-pair
sexy-internal-pair-drop
sexy-internal-pair-has?
sexy-internal-pair-head
sexy-internal-pair-reverse
sexy-internal-pair-size
sexy-internal-pair-tail
sexy-internal-pair-take
sexy-internal-pair-to-record
sexy-internal-pair-to-text
sexy-internal-pair-to-vector
sexy-internal-pair-view
sexy-internal-proc
sexy-internal-proc-arity
sexy-internal-proc-code
sexy-internal-proc-env
sexy-internal-proc-formals
sexy-internal-proc-to-text
sexy-internal-record-clone
sexy-internal-record-del!
sexy-internal-record-get
sexy-internal-record-has?
sexy-internal-record-keys
sexy-internal-record-merge
sexy-internal-record-put
sexy-internal-record-rm
sexy-internal-record-set!
sexy-internal-record-size
sexy-internal-record-to-list
sexy-internal-record-to-text
sexy-internal-record-values
sexy-internal-round
sexy-internal-rune-alpha?
sexy-internal-rune-digit?
sexy-internal-rune-lc
sexy-internal-rune-lc?
sexy-internal-rune-to-int
sexy-internal-rune-uc
sexy-internal-rune-uc?
sexy-internal-rune-whitespace?
sexy-internal-sink-flush
sexy-internal-sink-newline
sexy-internal-sink-print
sexy-internal-sink-view
sexy-internal-source-peek-rune
sexy-internal-source-read
sexy-internal-source-read-line
sexy-internal-source-read-lines
sexy-internal-source-read-rune
sexy-internal-source-read-sexy
sexy-internal-source-read-text
sexy-internal-source-view
sexy-internal-stream-close
sexy-internal-stream-open?
sexy-internal-stream-ready?
sexy-internal-symbol-to-text
sexy-internal-text
sexy-internal-text-capture
sexy-internal-text-chomp
sexy-internal-text-clone
sexy-internal-text-drop
sexy-internal-text-match
sexy-internal-text-pad-left
sexy-internal-text-pad-right
sexy-internal-text-ref
sexy-internal-text-replace
sexy-internal-text-set!
sexy-internal-text-size
sexy-internal-text-split
sexy-internal-text-subtext-index
sexy-internal-text-take
sexy-internal-text-to-bin
sexy-internal-text-to-keyword
sexy-internal-text-to-list
sexy-internal-text-to-number
sexy-internal-text-to-stream
sexy-internal-text-to-symbol
sexy-internal-text-trim
sexy-internal-text-trim-left
sexy-internal-text-trim-right
sexy-internal-truncate
sexy-internal-vector-drop
sexy-internal-vector-has?
sexy-internal-vector-ref
sexy-internal-vector-size
sexy-internal-vector-take
sexy-internal-vector-to-list
sexy-internal-vector-to-record
sexy-internal-vector-to-text
sexy-internal-vector-view
sexy-internal-λ-to-text
sexy-internal-this-name-is-about-to-be-defined
sexy-internal-this-name-was-not-found

