
(define true #t)
(define false #f)
(define null 'null)

(define global
    (environment
        identity
        handler
        (record 'env-type 'immutable)
        'send send
        'apply apply
        ...))

sexy-internal-get-object-type
sexy-internal-main-module
sexy-internal-object-answers?
sexy-internal-object-autos
sexy-internal-object-default
sexy-internal-object-get-message
sexy-internal-object-messages
sexy-internal-object-resends
sexy-internal-primitive-abs
sexy-internal-primitive-apply
sexy-internal-primitive-bin-to-text
sexy-internal-primitive-ceil
sexy-internal-primitive-env-def!
sexy-internal-primitive-env-del!
sexy-internal-primitive-env-extend
sexy-internal-primitive-env-get
sexy-internal-primitive-env-has?
sexy-internal-primitive-env-lookup
sexy-internal-primitive-env-lookup-list
sexy-internal-primitive-env-mama
sexy-internal-primitive-env-partition
sexy-internal-primitive-env-set!
sexy-internal-primitive-env-size
sexy-internal-primitive-env-to-list
sexy-internal-primitive-env-to-record
sexy-internal-primitive-env-to-text
sexy-internal-primitive-floor
sexy-internal-primitive-int-to-rune
sexy-internal-primitive-list
sexy-internal-primitive-list?
sexy-internal-primitive-list-ref
sexy-internal-primitive-list-to-text
sexy-internal-primitive-not
sexy-internal-primitive-number-to-text
sexy-internal-primitive-operator-to-text
sexy-internal-primitive-pair
sexy-internal-primitive-pair-drop
sexy-internal-primitive-pair-has?
sexy-internal-primitive-pair-head
sexy-internal-primitive-pair-reverse
sexy-internal-primitive-pair-size
sexy-internal-primitive-pair-tail
sexy-internal-primitive-pair-take
sexy-internal-primitive-pair-to-record
sexy-internal-primitive-pair-to-text
sexy-internal-primitive-pair-to-vector
sexy-internal-primitive-pair-view
sexy-internal-primitive-proc
sexy-internal-primitive-proc-arity
sexy-internal-primitive-proc-code
sexy-internal-primitive-proc-env
sexy-internal-primitive-proc-formals
sexy-internal-primitive-proc-to-text
sexy-internal-primitive-record-clone
sexy-internal-primitive-record-del!
sexy-internal-primitive-record-get
sexy-internal-primitive-record-has?
sexy-internal-primitive-record-keys
sexy-internal-primitive-record-merge
sexy-internal-primitive-record-put
sexy-internal-primitive-record-rm
sexy-internal-primitive-record-set!
sexy-internal-primitive-record-size
sexy-internal-primitive-record-to-list
sexy-internal-primitive-record-to-text
sexy-internal-primitive-record-values
sexy-internal-primitive-round
sexy-internal-primitive-rune-alpha?
sexy-internal-primitive-rune-digit?
sexy-internal-primitive-rune-lc
sexy-internal-primitive-rune-lc?
sexy-internal-primitive-rune-to-int
sexy-internal-primitive-rune-uc
sexy-internal-primitive-rune-uc?
sexy-internal-primitive-rune-whitespace?
sexy-internal-primitive-sink-flush
sexy-internal-primitive-sink-newline
sexy-internal-primitive-sink-print
sexy-internal-primitive-sink-view
sexy-internal-primitive-source-peek-rune
sexy-internal-primitive-source-read
sexy-internal-primitive-source-read-line
sexy-internal-primitive-source-read-lines
sexy-internal-primitive-source-read-rune
sexy-internal-primitive-source-read-sexy
sexy-internal-primitive-source-read-text
sexy-internal-primitive-source-view
sexy-internal-primitive-stream-close
sexy-internal-primitive-stream-open?
sexy-internal-primitive-stream-ready?
sexy-internal-primitive-symbol-to-text
sexy-internal-primitive-text
sexy-internal-primitive-text-capture
sexy-internal-primitive-text-chomp
sexy-internal-primitive-text-clone
sexy-internal-primitive-text-drop
sexy-internal-primitive-text-match
sexy-internal-primitive-text-pad-left
sexy-internal-primitive-text-pad-right
sexy-internal-primitive-text-ref
sexy-internal-primitive-text-replace
sexy-internal-primitive-text-set!
sexy-internal-primitive-text-size
sexy-internal-primitive-text-split
sexy-internal-primitive-text-subtext-index
sexy-internal-primitive-text-take
sexy-internal-primitive-text-to-bin
sexy-internal-primitive-text-to-keyword
sexy-internal-primitive-text-to-list
sexy-internal-primitive-text-to-number
sexy-internal-primitive-text-to-stream
sexy-internal-primitive-text-to-symbol
sexy-internal-primitive-text-trim
sexy-internal-primitive-text-trim-left
sexy-internal-primitive-text-trim-right
sexy-internal-primitive-truncate
sexy-internal-primitive-vector-drop
sexy-internal-primitive-vector-has?
sexy-internal-primitive-vector-ref
sexy-internal-primitive-vector-size
sexy-internal-primitive-vector-take
sexy-internal-primitive-vector-to-list
sexy-internal-primitive-vector-to-record
sexy-internal-primitive-vector-to-text
sexy-internal-primitive-vector-view
sexy-internal-primitive-λ-to-text
sexy-internal-record-get
sexy-internal-record-has?
sexy-internal-this-name-is-about-to-be-defined
sexy-internal-this-name-was-not-found

